version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    working_directory: ~/editor
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-deps
          command: npm install
      - run:
          name: lint
          command: npm run lint
      - run:
          name: build packages
          command: npm run build
      - persist_to_workspace:
          root: ~/editor
          paths:
              - "*"
  test:
    working_directory: ~/editor
    docker:
      - image: cimg/node:lts
    steps:
      - attach_workspace:
          at: ~/editor
      - run:
          name: run-tests
          command: npm run test
  integration:
    docker:
      - image: cypress/base:14.16.0
        environment:
          TERM: xterm
    working_directory: ~/editor
    steps:
      - attach_workspace:
          at: ~/editor
      - run:
          name: reinstall cypress binary
          command: npm install cypress
      - run: npm run integration:tests
  release:
    working_directory: ~/editor
    docker:
      - image: cimg/node:lts
    steps:
      - run:
          name: Create .ssh folder
          command: mkdir -p ~/.ssh
      - run:
          name: Add github.com to known hosts
          command: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - attach_workspace:
          at: ~/editor
      - run:
          name: Release new version
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/editor/.npmrc
            npm run release
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - integration:
          requires:
            - build
      - release:
          requires:
            - integration
            - build
            - test
          filters:
            branches:
              only:
                - main
